name = "aioban-api"
main = "src/index.ts"
compatibility_date = "2024-11-21"

[vars]
# Cambia esto por tu dominio front (p.ej., https://aioban.github.io)
ORIGIN = "https://aioban.github.io"

# Opcional: si querés usar el service role para upsert de perfil en /signup
USE_SERVICE_ROLE_FOR_PROFILE = "true"
